apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-deployment
  namespace: monitoring
  labels:
    app: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoring
  template: 
    metadata:
      name: monitoring
      labels:
        app: monitoring
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.18.0
        ports:
        - containerPort: 9090
      - name: grafana
        image: grafana/grafana:6.5.0
        ports:
        - containerPort: 3000

