apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: prod-namespace
  labels:
    app: redis
spec:
  replicas: 4
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers: 
      - name: redis
        image: redis:5
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-storage
          mountPath: /data/redis
      volumes:
      - name: redis-storage
        emptyDir: {}


      
