apiVersion: v1
kind: Service
metadata:
  name: grafana-svc-lb
  namespace: monitoring
spec:
  type: LoadBalancer
  #  loadBalancerIP: 10.164.0.100
  selector:
    app: monitoring-grafana
  ports:
  - name: grafana
    port: 3000
