apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: monitoring-grafana
  ports:
  - name: grafana
    port: 3000
    targetPort: 3002
    nodePort: 31111
