apiVersion: v1
kind: Service
metadata:
  name: monitoring-grafana-svc
  namespace: monitoring
spec:
  selector:
    app: monitoring
  ports:
  - name: grafana
    port: 3000
    targetPort: 3001
    nodePort: 31110
  type: NodePort
