apiVersion: v1
kind: Service
metadata:
  name: monitoring-svc
  namespace: monitoring
spec:
  selector:
    app: monitoring
  ports:
  - name: prometheus
    port: 9090
    targetPort: 9091
    nodePort: 31300
  - name: grafana
    port: 3000
    targetPort: 3001
    nodePort: 31100
  type: NodePort
