apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: monitoring-prom
  ports:
  - name: prometheus
    port: 9090
    targetPort: 9092
    nodePort: 31310
